package com.example.demo.config;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Map;

@Component
public class TenantSchemaInitializer implements ApplicationRunner {

    private final Map<String, DataSource> tenantDataSources;

    public TenantSchemaInitializer(@Qualifier("tenantDataSources") Map<String, DataSource> tenantDataSources) {
        this.tenantDataSources = tenantDataSources;
    }

    @Override
    public void run(ApplicationArguments args) {
        for (Map.Entry<String, DataSource> entry : tenantDataSources.entrySet()) {
            DataSource ds = entry.getValue();
            try (Connection conn = ds.getConnection();
                 Statement stmt = conn.createStatement()) {
                String dbProduct = conn.getMetaData().getDatabaseProductName().toLowerCase();
                if (dbProduct.contains("h2")) {
                    stmt.execute("CREATE TABLE IF NOT EXISTS users (" +
                            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "name VARCHAR(255) NOT NULL, " +
                            "email VARCHAR(255) NOT NULL" +
                            ")");
                } else {
                    stmt.execute("CREATE TABLE IF NOT EXISTS users (" +
                            "id BIGSERIAL PRIMARY KEY, " +
                            "name VARCHAR(255) NOT NULL, " +
                            "email VARCHAR(255) NOT NULL" +
                            ")");
                }
            } catch (Exception e) {
                // Log and continue initialization
                System.err.println("Schema initialization for tenant " + entry.getKey() + " failed: " + e.getMessage());
            }
        }
    }
}
